name: positive_phill
description: "\"Positive Phill\" is a calming and empowering mobile app designed to uplift your spirits daily with personalized affirmations, gamified progress tracking, and a premium, modern user experience."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  url_launcher: ^6.3.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0
  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.0.0
  webview_flutter: ^4.0.0
  confetti: 0.8.0
  share_plus: ^12.0.0
  flutter_vibrate: ^1.0.0
  flutter_tts: ^4.2.5
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  package_info_plus: ^9.0.0
  in_app_review: ^2.0.11
  image_picker: ^1.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    background_color: "#121212"
    theme_color: "#8FE6D6"
  image_path: assets/icons/icon.png
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#121212"
  image: assets/splash.png
  android_12:
    color: "#121212"
    image: assets/splash.png
  web: false



